apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-alerts
  namespace: monitoring
  labels:
    release: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  groups:
  - name: backend.rules
    rules:
    - alert: BackendDown
      expr: absent(up{job="backend-service", namespace="backend"})
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "All backend pods are down"
        description: "Prometheus cannot find any 'up' targets for the backend service."

    - alert: NoTraffic
      expr: |
        sum(rate(app_requests_total{namespace="backend"}[2m])) == 0 
        or 
        absent(app_requests_total{namespace="backend"})
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "No traffic detected on Backend"
        description: "The backend has processed zero requests. Check Ingress/ALB."

    - alert: DatabaseIssues
      expr: app_db_request_count{namespace="backend"} == 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "App reporting 0 database hits"
        description: "The DB_REQUEST_COUNT gauge is at 0. The app might be failing to write to the RDS instance."