apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: backend 
  namespaceSelector:
    matchNames:
      - backend
  endpoints:
    - port: http
      path: /metrics
      interval: 10s