apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - backend
  endpoints:
    - name: "http-backend"
      port: 80
      targetPort: 8000
      path: /metrics
      interval: 10s