apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-db-secrets
  namespace: backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "db-credentials"
        objectType: "secretsmanager"

  secretObjects:
    - secretName: backend-db-secret
      type: Opaque
      data:
        - objectName: db-credentials
          key: username
          objectAlias: DB_USER
        - objectName: db-credentials
          key: password
          objectAlias: DB_PASSWORD
        - objectName: db-credentials
          key: dbname
          objectAlias: DB_NAME
        - objectName: db-credentials
          key: host
          objectAlias: DB_HOST
        - objectName: db-credentials
          key: port
          objectAlias: DB_PORT