apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-db-secrets
  namespace: backend
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: host
            objectAlias: DB_HOST
          - path: port
            objectAlias: DB_PORT
          - path: username
            objectAlias: DB_USER
          - path: password
            objectAlias: DB_PASSWORD
          - path: dbname
            objectAlias: DB_NAME