apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-spc
  namespace: backend
spec:
  provider: aws
  secretObjects:
    - secretName: backend-db-secret
      type: Opaque
      data:
        - objectName: db_password 
          key: DB_PASSWORD     
        - objectName: db_host
          key: DB_HOST
        - objectName: db_user
          key: DB_USER
        - objectName: db_name
          key: DB_NAME
  parameters:
    objects: |
      - objectName: "db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: db_password
          - path: host
            objectAlias: db_host
          - path: username
            objectAlias: db_user
          - path: dbname
            objectAlias: db_name