apiVersion: v1
kind: Service
metadata:
  name: backend-v1-service
  namespace: backend
spec:
  selector:
    app: backend
    version: v1
  ports:
    - name: http
      port: 8000
      targetPort: 8000