apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      containers:
        - name: frontend
          image: 284432073095.dkr.ecr.us-east-1.amazonaws.com/frontend-v2:18be8be9af57013f21b5ed7055a1c826cb2f052f
          imagePullPolicy: Always
          ports:
            - containerPort: 8080