apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      containers:
        - name: frontend
          image: 284432073095.dkr.ecr.us-east-1.amazonaws.com/frontend-v2:7b8d0b03d82e4318517b4ae696142b8599ed3725
          imagePullPolicy: Always
          ports:
            - containerPort: 8080