apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 57.x.x
    helm:
      values: |
        grafana:
          adminPassword: "admin" # Change this for production!
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
        prometheusOperator:
          admissionWebhooks:
            patch: 
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true